public class JanelaResultado extends javax.swing.JFrame {
    //JogoEmSi jogo = new JogoEmSi();
    public JanelaResultado() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPergunta1 = new javax.swing.JLabel();
        lblResposta1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("São Luís");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPergunta1.setFont(new java.awt.Font("Droid Sans", 1, 22)); // NOI18N
        lblPergunta1.setText(pergunta1);
        getContentPane().add(lblPergunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 123, -1, -1));

        lblResposta1.setFont(new java.awt.Font("Serif", 1, 23)); // NOI18N
        lblResposta1.setForeground(new java.awt.Color(245, 251, 35));
        lblResposta1.setText(alternativa_certa1);
        getContentPane().add(lblResposta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 311, -1, -1));

        jLabel1.setFont(new java.awt.Font("Droid Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 76, 171));
        jLabel1.setText("Resultado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bitstream Charter", 1, 23)); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 30, 20));

        btnNext.setFont(new java.awt.Font("Noto Sans", 1, 27)); // NOI18N
        btnNext.setForeground(new java.awt.Color(0, 240, 255));
        btnNext.setText(">");
        btnNext.setContentAreaFilled(false);
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.setFocusPainted(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 150, 60));

        jLabel3.setBackground(java.awt.Color.black);
        jLabel3.setFont(new java.awt.Font("Droid Sans Mono", 3, 23)); // NOI18N
        jLabel3.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(29, 51));
        jButton1.setMinimumSize(new java.awt.Dimension(29, 51));
        jButton1.setPreferredSize(new java.awt.Dimension(29, 51));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 550, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosvisuais/Photos-Downlload-Free-HD-Solid-Color-Wallpaper.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-480, -280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int i = 0;
    public void erro(String erro){
        error = erro;
        System.out.println(error);
    };  
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (i >= 14){
            if("Página inicial".equals(btnNext.getText())){
                JanelaSaoLuis lala = new JanelaSaoLuis();
                lala.setVisible(true);
                dispose();
        }
            lblPergunta1.setText("");
            lblResposta1.setText("");
            jLabel3.setText("Respostas Erradas: ");
            jLabel4.setText(error);
            btnNext.setText("Página inicial");
            btnNext.setBackground(java.awt.Color.BLUE);
            btnNext.setFont(new java.awt.Font("NanumGothic", 1, 16)); // NOI18N
            btnNext.setForeground(java.awt.Color.white);
            btnNext.setToolTipText("Início");
            btnNext.setFocusPainted(true);
          //  btnNext.setBorder(BorderFactory.createLineBorder(Color.black, 1));
            btnNext.setContentAreaFilled(true);
            jButton1.setText("Novo Jogo");
            jButton1.setBackground(java.awt.Color.CYAN);
            jButton1.setFont(new java.awt.Font("NanumGothic", 1, 16)); // NOI18N
            jButton1.setForeground(java.awt.Color.DARK_GRAY);
            jButton1.setToolTipText("Jogar Novamente?");
            jButton1.setContentAreaFilled(true);
            
                        }
        else{
        lblPergunta1.setText(coisas[i]);
        lblResposta1.setText(coisa[i]);
        }
        i++;
        
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ("Novo Jogo".equals(jButton1.getText())){
            JogoEmSi again = new JogoEmSi();
            again.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    String error = "";
    String pergunta1 = "Qual era o interesse dos franceses no Norte do Brasil?"+i;
    String alternativa_certa1 = "Fundar uma colônia";
       
    
    //Segunda Pergunta
    String pergunta2 = "Nome do Lider francês?";
    String alternativa_certa2 = "Daniel de La Touche";
    
    //Terceira Pergunta
    String pergunta3 = "Palácio que os franceses criaram: ";
    String alternativa_certa3 = "Palácio dos Leões";
   
    
    //Quarta Pergunta
    String pergunta4 = "Em que local do Brasil os franceses desembarcaram?";
    String alternativa_certa4 = "Ilha de Upaon-Açu";
    
    //Quinta Pergunta
    String pergunta5 = "Quem era o comandante do exército português que lutou contra os franceses?";
    String alternativa_certa5 = "Jerônimo de Albuquerque";
   
    
    //Sexta Pergunta
    String pergunta6 = "O forte construído pelos franceses em São Luís foi primeiramente chamado de...";
    String alternativa_certa6 = "Fort Saint Louis";
   
    
    //Sétima Pergunta
    String pergunta7 = "O que foi a \"Jornada Milagrosa\"?";
    String alternativa_certa7 = "A expedição portuguesa contra a França";
    String alternativa2_7 = "O difícil caminho percorrido pelos franceses";
    String alternativa3_7 = "A resistência indígena contra a ocupação";
    
    //Oitava Pergunta
    String pergunta8 = "Um dos principais motivos da falta de arquitetura francesa em São Luís, é...";
    String alternativa_certa8 = "Destruição de qualquer estrutura criada pelos franceses";
   
    //Nona Pergunta
    String pergunta9 = "A batalha de Guaxenduba foi...";
    String alternativa_certa9 = "Um confronto decisivo entre franceses e portugueses";
    
    //Décima Pergunta
    String pergunta10 = "Tentativa de formar uma colônia francesa no norte dos territórios da América: ";
    String alternativa_certa10 = "França Equinocial";
   
    String pergunta11 = "Desfecho da batalha de Guaxenduba";
    String alternativa_certa11 = "Franceses derrotados";
    
    String pergunta12 = "Após a derrota, Daniel de la Touche...";
    String alternativa_certa12 = "Foi rendido e preso em Lisboa";
    
    String pergunta13 = "Forte feito pelos portugueses em Guaxenduba";
    String alternativa_certa13 = "Forte de Santa Maria de Guaxenduba";
    
    String pergunta14 = "Depois da derrota de Daniel de La Touche, Jerônimo de Albuquerque: ";
    String alternativa_certa14 = "Se tornou governador do Maranhão";
    
    String pergunta15 = "Conclusão: ";
    String alternativa_certa15 = "Os franceses invadiram, e os portugueses fundaram São Luís";
   
    String coisas[] = {pergunta2, pergunta3, pergunta4, pergunta5, pergunta6,pergunta7, pergunta8, pergunta9, pergunta10, pergunta11, pergunta12, pergunta13, pergunta14, pergunta15};
    String coisa[] = {alternativa_certa2,alternativa_certa3,alternativa_certa4,alternativa_certa5,alternativa_certa6,alternativa_certa7,alternativa_certa8,alternativa_certa9,alternativa_certa10, alternativa_certa11, alternativa_certa12, alternativa_certa13, alternativa_certa14, alternativa_certa15};
    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaResultado().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnNext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblPergunta1;
    private javax.swing.JLabel lblResposta1;
    // End of variables declaration//GEN-END:variables
    
    
}

